version: 2
jobs:
  build:
    docker:
      - image: 'fpco/stack-build:latest'
    steps:
      - checkout
      - restore_cache:
          key: 'v3-hakyll-{{ arch }}-{{ .Branch }}'
      - run:
          # We set jobs to 1 here because that prevents Out-Of-Memory exceptions
          # while compiling dependencies.
          name: 'Install dependencies'
          command: '.circleci/tickle.sh stack build --test --copy-bins --jobs=1'
      - save_cache:
          key: 'v3-hakyll-{{ arch }}-{{ .Branch }}-{{ .Revision }}'
          paths:
            - '~/.stack-work'
            - '~/.stack'
